### ISSUE TITLE
Tables strokes show even when they are set to 0pt.

### ISSUE THREAD

**Issue by UGL1** [typst/typst#1018]
### Description

```typst
#table(
  columns: (1fr,1fr),
  stroke: 0pt,
  [foo],
  [bar]
)
```
Shows ok in the web app but export and local compilation show strokes.

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
This was fixed in v0.3.0, make sure to update your local typst build (check `typst --version`)

**Comment by laurmaedje** [comment]
@PgBiel I just checked and it's actually not fixed for PDF export.

**Comment by PgBiel** [comment]
> @PgBiel I just checked and it's actually not fixed for PDF export.

Well darn... looks like I did an oopsie! Hahaha...
Will be submitting a PR ASAP, sorry for the inconvenience!

**Comment by PgBiel** [comment]
Maybe in the future we should add a test suite for PDFs as well, just in case :sweat_smile: 
But that was really a huge miss on my part, my bad :p
