### ISSUE TITLE
alphanumerical citing style ignores supplement

### ISSUE THREAD

**Issue by tjueterb** [typst/typst#1330]
### Description

This should be easily fixable.

    #set cite(style: "numerical")
    @reference_key[p.~7]

produces "[1, p. 7]" as expected, while

    #set cite(style: "alphanumerical")
    @reference_key[p.~7]

omits the "p. 7" supplement.
 

### Reproduction URL

https://typst.app/project/wCb1Kl7auyH3kadjEsix5M

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by lynn** [comment]
I tracked this down to hayagriva: https://github.com/typst/hayagriva/issues/48.

**Comment by laurmaedje** [comment]
I updated the hayagriva dependency and the bug was already fixed there, so this should be fixed now.

**Comment by janosh** [comment]
i'm still seeing this problem with `"future-science"`.

```typ
set cite(style: "future-science")

This has been proven. @distress[p.~7]

#bibliography("works.bib")
```

renders only `[1]`, no `p. 7`. open a new issue?

**Comment by lukasjuhrich** [comment]
What do I have to do in order to obtain the fix for this? The latest typst v0.11 appears to still have this issue: the MWE @tjueterb provided still shows the issue in the web app. I [double checked](https://typst.app/project/rawQ3hbHaDP1CbnPKF6PLI) just to be sure. I can also reproduce the error locally.

I have no idea what version of hayagriva is in that version of typst, as `typst --version` does not include that information.

**Comment by laurmaedje** [comment]
Hayagriva was rewritten since that PR and the new alphanumeric style has regressed the problem. I've reopened https://github.com/typst/hayagriva/issues/48. Let's leave this issue here closed still since we don't need duplicate open issues across the Typst-owned repositories.

**Comment by lukasjuhrich** [comment]
> Let's leave this issue here closed still since we don't need duplicate open issues across the Typst-owned repositories.

Sure, thanks for the quick reaction!
