### ISSUE TITLE
Proper kerning of minus sign in math mode

### ISSUE THREAD

**Issue by gabrfarina** [typst/typst#577]
The minus sign is often not positioned correctly (too much horizontal space) when used to denote a negative number: for example

<img width="227" alt="image" src="https://user-images.githubusercontent.com/737249/229858926-db68c0cc-6a1f-4062-ada8-4668f58cd0a4.png">

where only the first "-1" is displayed correctly.

Expected behavior:
<img width="227" alt="image" src="https://user-images.githubusercontent.com/737249/229859281-4a4d457c-d123-4f38-a317-f8bdde05b605.png">

I'd be happy to try to fix this with enough hints for where to look from the maintainers.

**Comment by laurmaedje** [comment]
This is already fixed on main. There'll be a new release later today. :)

**Comment by gabrfarina** [comment]
Thanks @laurmaedje . I pulled and built from sources, and I still see this:

<img width="74" alt="image" src="https://user-images.githubusercontent.com/737249/229953495-832f88e9-0dc7-4d51-aee4-1bc3bff45c61.png">

Am I doing something wrong?

**Comment by laurmaedje** [comment]
what does `typst -V` output?

**Comment by memeplex** [comment]
I'm still seeing some related issues in 0.13:

```
$"with" -1 < x < 1$
```

Renders like this: 

<img width="142" alt="Image" src="https://github.com/user-attachments/assets/dc5f573e-cc6c-429e-9159-cb0399b5f812" />

**Comment by mkorje** [comment]
@memeplex Minus has math class vary, so the "with" preceding it makes it have spacing like a binary operator instead of a unary one. I'm not sure if we can improve the situation here as you could write something like `$"value"-1<x<1$`, in which case the minus *should* be treated as a binary operator.

I think the "correct" thing to do would be to specify a space in the code. (Doesn't have to be `space` specifically.)

```typ
$ "with" -1 < x < 1 $
$ "with " - 1 < x < 1 $
$ "with" space - 1 < x < 1 $
```

![Image](https://github.com/user-attachments/assets/6675f917-db79-4e1b-8a5a-28998a2adadf)

**Comment by memeplex** [comment]
I understand, thanks for the explanation and the workaround! Perhaps something like minus(1) could be added, in order to resolve the ambiguity in a more meaningful way. I mean not particularly minus(1) which is already taken but something along the lines. Anyway, you know better than me.

**Comment by memeplex** [comment]
Oh, this also works `$"with" #box[-1] < x < 1$` and I find it quite natural. I'm good with it.
