### ISSUE TITLE
Gradients on `curve` elements don't use the correct bounding box when last segment is `curve.line`

### ISSUE THREAD

**Issue by Mc-Zen** [typst/typst#6068]
### Description

Consider
```typ
#curve(  
  curve.line((40pt, 40pt)),
  stroke: gradient.linear(blue, red).sharp(2)
)
```
Due to the sharp gradient, we expect a line that is half red and half blue but actually it is rendered 
- entirely blue with `png` and
- entirely red with `pdf` and `svg` export. 

The issue **does not occur** with
- `path`
  ```typ
  #path(
    (0pt, 0pt),
    (40pt, 40pt),
    stroke: gradient.linear(blue, red).sharp(2)
  )
  ```
- when using a `curve.quad` or `curve.cubic` element, e.g., 
  ```typ
  #curve(  
    curve.quad(none, (40pt, 40pt)),
    stroke: gradient.linear(blue, red).sharp(2)
  )
  ```

Note that this has nothing to do with sharp gradients, they are just better to demonstrate the issue. 

### Typst version

- [x] I am using the latest version of Typst

**Comment by Mc-Zen** [comment]
Actually there's more weird things

```typ
#let stroke = gradient.linear(blue, red).sharp(2)

#line(start: (0pt, 0pt), end: (100pt, 0pt), stroke: stroke)
#curve(
  curve.quad(none, (100pt, 0pt)),
  stroke: stroke
)
#path(
  (0pt, 0pt),
  (100pt, 0pt),
  stroke: stroke
)
```

![Image](https://github.com/user-attachments/assets/1c00cee0-7cdb-4a35-bb37-394aea2d7d9f)

Curve and path seem to agree but I'd expect them to all produce the same result because
```typ
#line(start: (0pt, 0pt), end: (100pt, 0pt), stroke: stroke)
#curve(
  curve.quad(none, (100pt, 0pt)),
  curve.quad(none, (100pt, 10pt)),
  stroke: stroke
)
#path(
  (0pt, 0pt),
  (100pt, 0pt),
  (100pt, 10pt),
  stroke: stroke
)
```

![Image](https://github.com/user-attachments/assets/15745be7-a84f-48f2-bade-dea24a342972)

At last:
```typ
#line(start: (25pt, 0pt), end: (100pt, 0pt), stroke: stroke)
#curve(
  curve.move((25pt, 0pt)),
  curve.quad(none, (100pt, 0pt)),
  curve.quad(none, (100pt, 10pt)),
  stroke: stroke
)
#path(
  (25pt, 0pt),
  (100pt, 0pt),
  (100pt, 10pt),
  stroke: stroke
)
```

![Image](https://github.com/user-attachments/assets/4514fdf8-be18-4ace-9868-bfc8f265cf90)

**Comment by laurmaedje** [comment]
Potentially fixed by https://github.com/typst/typst/pull/6647?

**Comment by ParaN3xus** [comment]
The minimal case has been fixed for SVG and PNG outputs, but the `gradient` is no longer sharp in PDF output

**Comment by eltos** [comment]
Gradients on curves are still broken (WebApp Development Version as of 5.2.2026):

Images below are PNG export, but SVG and PDF show simmilar issues



```typ
#set page(width: auto, height: auto, margin: 5pt)
#for angle in (0deg, 45deg, 90deg, 180deg){
  box(width: 50pt, height: 50pt, {
    let g = gradient.linear(yellow, black, angle: angle).sharp(4)
    place(dx: 20pt, dy: 20pt, circle(radius: 5pt, fill: g))
    for i in range(0,12){
      place(dx: 25pt + 6pt*calc.cos(i*30deg), dy: 25pt + 6pt*calc.sin(i*30deg),
        curve(
          stroke: g + 5pt,
          curve.move((0pt, 0pt)),
          curve.line((18pt * calc.cos(i*30deg), 18pt * calc.sin(i*30deg))),
        )
      )
    }
  })
}
```

<img width="875" height="250" alt="Image" src="https://github.com/user-attachments/assets/fa67b029-8e8e-41e3-a352-1125c2248f2b" />

-----------

```typ
#set page(width: auto, height: auto, margin: 5pt)
#for angle in (0deg, 45deg, 90deg, 180deg){
  box(width: 50pt, height: 50pt, {
    let g = gradient.linear(yellow, black, angle: angle).sharp(4)
    place(dx: 20pt, dy: 20pt, circle(radius: 5pt, fill: g))
    for i in range(0,12){
      place(dx: 25pt + 6pt*calc.cos(i*30deg), dy: 25pt + 6pt*calc.sin(i*30deg),
        curve(
          stroke: g + 5pt,
          curve.move((0pt, 0pt)),
          curve.quad((9pt * calc.cos((i+1)*30deg), 9pt * calc.sin((i+1)*30deg)), (18pt * calc.cos(i*30deg), 18pt * calc.sin(i*30deg))),
        )
      )
    }
  })
}
```

<img width="875" height="250" alt="Image" src="https://github.com/user-attachments/assets/0691307f-a32b-445f-9c2b-a52737eb5dde" />

--------------

Gradients on lines are somewhat broken too:

```typ
#set page(width: auto, height: auto, margin: 5pt)
#for angle in (0deg, 45deg, 90deg, 180deg){
  box(width: 50pt, height: 50pt, {
    let g = gradient.linear(yellow, black, angle: angle).sharp(4)
    place(dx: 20pt, dy: 20pt, circle(radius: 5pt, fill: g))
    for i in range(0,12){
      place(dx: 25pt + 6pt*calc.cos(i*30deg), dy: 25pt + 6pt*calc.sin(i*30deg),
        line(length: 18pt, angle: i*30deg, stroke: g + 5pt)
      )
    }
  })
}
```

<img width="875" height="250" alt="Image" src="https://github.com/user-attachments/assets/2ea26cad-bb8b-47d4-8453-7ec72e83b0ce" />
