### ISSUE TITLE
Adding an SVG image containing `<text>` with different font styles leads to non-deterministic compilation results.

### ISSUE THREAD

**Issue by ensko** [typst/typst#6783]
### Description

Steps to reproduce: compile this document multiple times to PDF (with Typst 0.13.1) and compare the results:
```typ
#set document(date: none)
#set page(width: auto, height: auto, margin: 0pt)

#image(bytes(`
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg width="15pt" height="9pt" viewBox="0 0 15 9" version="1.1" id="svg5"
   xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
   <defs id="defs2" />
   <g id="layer1">
      <text style="font-size:12px;line-height:1.25;font-family:sans-serif;stroke-width:0.749947"
         xml:space="preserve" x="0.5" y="7.5" id="text113">a</text>
      <text
         style="font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-size:12px;line-height:1.25;font-family:sans-serif;-inkscape-font-specification:'sans-serif Bold';stroke-width:0.750067"
         xml:space="preserve" x="7.5" y="7.5" id="text167">a</text>
   </g>
</svg>
`.text.trim()))
```

The SVG is out of inkscape, lightly edited for terseness.

Expected result: all compilations result in byte-identical results.
Actual result: it seems that PDF sections relating to the two font variants can be switched non-deterministically. (The visual result is identical.)

Here are some excerpts from the diff of two resulting PDFs (it seems like I can't attach them, but it's fairly simple to reproduce):
```diff
diff --git a/a.pdf b/a.pdf
--- a/a.pdf
+++ b/a.pdf
@@ -11,8 +11,8 @@
   /Filter /FlateDecode
   /Resources <<
     /Font <<
-      /fo0 4 0 R
-      /fo1 5 0 R
+      /fo1 4 0 R
+      /fo0 5 0 R
     >>
     /ColorSpace <<
       /cs0 [/ICCBased 6 0 R]
@@ -30,7 +30,7 @@ endobj
 <<
   /Type /Font
   /Subtype /Type0
-  /BaseFont /UPVDXZ+LibertinusSerif-Regular-Identity-H
+  /BaseFont /ZQVXKE+LibertinusSerif-Bold-Identity-H
   /Encoding /Identity-H
   /DescendantFonts [7 0 R]
   /ToUnicode 8 0 R
@@ -41,7 +41,7 @@ endobj
 <<
   /Type /Font
   /Subtype /CIDFontType0
-  /BaseFont /UPVDXZ+LibertinusSerif-Regular
+  /BaseFont /ZQVXKE+LibertinusSerif-Bold
   /CIDSystemInfo <<
     /Registry (Adobe)
     /Ordering (Identity)
...
@@ -128,7 +125,7 @@ endobj
 <<
   /Type /Font
   /Subtype /Type0
-  /BaseFont /ZQVXKE+LibertinusSerif-Bold-Identity-H
+  /BaseFont /UPVDXZ+LibertinusSerif-Regular-Identity-H
   /Encoding /Identity-H
   /DescendantFonts [11 0 R]
   /ToUnicode 12 0 R
@@ -139,7 +136,7 @@ endobj
 <<
   /Type /Font
   /Subtype /CIDFontType0
-  /BaseFont /ZQVXKE+LibertinusSerif-Bold
+  /BaseFont /UPVDXZ+LibertinusSerif-Regular
   /CIDSystemInfo <<
     /Registry (Adobe)
     /Ordering (Identity)
...
```

### Operating system

Linux

### Typst version

- [x] I am using the latest version of Typst

**Comment by LaurenzV** [comment]
I'm pretty certain that this should already be fixed in the development version, but haven't tested it yet.

**Comment by tovrstra** [comment]
I just tested this with 88b6fc0a6ccd517b38c6534f16c88763e5545617 (commit of 2029-09-12) and the issue still persists.

Possibly related to #6823?

**Comment by LaurenzV** [comment]
I’ll see whether I can take a look.

**Comment by laurmaedje** [comment]
I can reproduce this neither with https://github.com/typst/typst/commit/88b6fc0a6ccd517b38c6534f16c88763e5545617 nor with main.

**Comment by laurmaedje** [comment]
With 0.13.1, in contrast, I can reproduce it. 

@tovrstra Are you sure you can still reproduce this?

**Comment by tovrstra** [comment]
I can still reproduce it with main (4f9b9a97dca83ce2018a9395d4853208aa4b7b24), as shown below. There could be a few explanations:

- This could be OS-related. I'm testing on Fedora Linux 42.
- Because the behavior is random, it may take multiple attempts to produce two different PDFs.

This is what I did exactly:

```bash
typst compile nonrep.typ nonrep1.pdf
typst compile nonrep.typ nonrep2.pdf  # Repeat until the second PDF has a different shasum
shasum nonrep1.pdf nonrep2.pdf
diff -a nonrep1.pdf nonrep2.pdf
```

The shasum output:

```text
e295f1e11ec5b7da1bfcb82d47bff6caafb5c121  nonrep1.pdf
a73de149fb5e8ba30450737abf3d538df9647e17  nonrep2.pdf
```

The diff output (-a forces diff to treat the files as text):

```diff
14,15c14,15
<       /fo0 4 0 R
<       /fo1 5 0 R
---
>       /fo1 4 0 R
>       /fo0 5 0 R
33c33
<   /BaseFont /ZQVXKE+LibertinusSerif-Bold-Identity-H
---
>   /BaseFont /UPVDXZ+LibertinusSerif-Regular-Identity-H
44c44
<   /BaseFont /ZQVXKE+LibertinusSerif-Bold
---
>   /BaseFont /UPVDXZ+LibertinusSerif-Regular
52c52
<   /W [0 0 500 1 1 506]
---
>   /W [0 0 500 1 1 457]
59c59
<   /FontName /ZQVXKE+LibertinusSerif-Bold
---
>   /FontName /UPVDXZ+LibertinusSerif-Regular
61c61
<   /FontBBox [-6275 -328 6171 1014.00006]
---
>   /FontBBox [-6275 -256 6171 1125]
65,66c65,66
<   /CapHeight 645
<   /StemV 168.6
---
>   /CapHeight 658
>   /StemV 95.4
114c114
<   /Length 485
---
>   /Length 499
119,120c119,123
< x�E�Oh�`ƿ�m��~Vl�1L���ݜ��E�B�����Z�H���ߨ k�N�B�
< ��Z�sn
        te"�g��iE�y��_����]~���</>�r�Ք�67qJ��
                                             ���x�␦I�w���-�?�?����������]m���6[-�KO�P���x!dC�i-�
                                                                                                ����␦�a�����C����r�< �Ngi��4�kc�yCJ䌌�O�� �s���yv����,�U�
                               O!ɵ�
                                   _pWw9h���4�����lYe����b#
�n�*|�[Ӝ����#T�olh$���G�}5��Q���7�\j���ƿ[~X_#��ʔ=iw�o槮����icpL�$�sCZ%��������LiF(:Eg��W�+��j�$��%&��;��ړ|9�Y{���(�q�#��˺~���^�-,�Y��X
             �X)�k
---
> x�E��Kqǿ_���y-r
                 o�1�°��␦�3�z��rc���� ��p�ُ]z9z)���
                                                  �/�AP=�zؓ��M���'����y>��@����dE�%�WY���+
                                                                                         $�7e�uY���h�j��~M�%M��ܵ�}^vs�h�k��C5V�t
     ��[q�Iww�_
> 
  ���"*#��Y�(��
> ��
    ������ߋ�_��;�-�%��$�OP c9+��͡ƙ���
��S�6��َb|iu���i��w��j:4��ٸTɐ��|     i�7(��0��~��/����t����8���

> "m�����`e�%����'�}}f� �h�tW,盆����㧧��+L4k
                                            ��r��\��N�&��e��S��Q6��-��
> ��yu��t_o<7���l!����cN}�f������⧤M�2��&<���k�:�}[�����{F<D=���FөinxHT$�z����B��
                                                                                �{Ü
128c131
<   /BaseFont /UPVDXZ+LibertinusSerif-Regular-Identity-H
---
>   /BaseFont /ZQVXKE+LibertinusSerif-Bold-Identity-H
139c142
<   /BaseFont /UPVDXZ+LibertinusSerif-Regular
---
>   /BaseFont /ZQVXKE+LibertinusSerif-Bold
147c150
<   /W [0 0 500 1 1 457]
---
>   /W [0 0 500 1 1 506]
154c157
<   /FontName /UPVDXZ+LibertinusSerif-Regular
---
>   /FontName /ZQVXKE+LibertinusSerif-Bold
156c159
<   /FontBBox [-6275 -256 6171 1125]
---
>   /FontBBox [-6275 -328 6171 1014.00006]
160,161c163,164
<   /CapHeight 658
<   /StemV 95.4
---
>   /CapHeight 645
>   /StemV 168.6
209c212
<   /Length 499
---
>   /Length 485
214,218c217,218
< x�E��Kqǿ_���y-r
                 o�1�°��␦�3�z��rc���� ��p�ُ]z9z)���
                                                  �/�AP=�zؓ��M���'����y>��@����dE�%�WY���+
                                                                                         $�7e�uY���h�j��~M�%M��ܵ�}^vs�h�k��C5V�t
     ��[q�Iww�_
< 
  ���"*#��Y�(��
< ��
    ������ߋ�_��;�-�%��$�OP c9+��͡ƙ���
��S�6��َb|iu���i��w��j:4��ٸTɐ��|     i�7(��0��~��/����t����8���

< "m�����`e�%����'�}}f� �h�tW,盆����㧧��+L4k
                                            ��r��\��N�&��e��S��Q6��-��
< ��yu��t_o<7���l!����cN}�f������⧤M�2��&<���k�:�}[�����{F<D=���FөinxHT$�z����B��
                                                                                �{Ü
---
> x�E�Oh�`ƿ�m��~Vl�1L���ݜ��E�B�����Z�H���ߨ k�N�B�
> ��Z�sn
        te"�g��iE�y��_����]~���</>�r�Ք�67qJ��
                                             ���x�␦I�w���-�?�?����������]m���6[-�KO�P���x!dC�i-�
                                                                                                ����␦�a�����C����r�< �Ngi��4�kc�yCJ䌌�O�� �s���yv����,�U�
                               O!ɵ�
                                   _pWw9h���4�����lYe����b#
�n�*|�[Ӝ����#T�olh$���G�}5��Q���7�\j���ƿ[~X_#��ʔ=iw�o槮����icpL�$�sCZ%��������LiF(:Eg��W�+��j�$��%&��;��ړ|9�Y{���(�q�#��˺~���^�-,�Y��X
             �X)�k
307c307
< <?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?><x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="xmp-writer"><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"><rdf:Description rdf:about="" xmlns:dc="http://purl.org/dc/elements/1.1/"  xmlns:xmp="http://ns.adobe.com/xap/1.0/"  xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"  xmlns:xmpTPg="http://ns.adobe.com/xap/1.0/t/pg/"  xmlns:pdf="http://ns.adobe.com/pdf/1.3/" ><xmp:CreatorTool>Typst 0.13.1</xmp:CreatorTool><xmpMM:DocumentID>HiQnxPhSaL50dAnsJIxLIQ==</xmpMM:DocumentID><xmpMM:InstanceID>HiQnxPhSaL50dAnsJIxLIQ==</xmpMM:InstanceID><dc:format>application/pdf</dc:format><pdf:PDFVersion>1.7</pdf:PDFVersion><dc:language><rdf:Bag></rdf:Bag></dc:language><xmpTPg:NPages>1</xmpTPg:NPages><xmpMM:RenditionClass>proof</xmpMM:RenditionClass></rdf:Description></rdf:RDF></x:xmpmeta><?xpacket end="r"?>
---
> <?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?><x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="xmp-writer"><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"><rdf:Description rdf:about="" xmlns:dc="http://purl.org/dc/elements/1.1/"  xmlns:xmp="http://ns.adobe.com/xap/1.0/"  xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"  xmlns:xmpTPg="http://ns.adobe.com/xap/1.0/t/pg/"  xmlns:pdf="http://ns.adobe.com/pdf/1.3/" ><xmp:CreatorTool>Typst 0.13.1</xmp:CreatorTool><xmpMM:DocumentID>U7DI7lZeRcvFEZ3TYxo3UA==</xmpMM:DocumentID><xmpMM:InstanceID>U7DI7lZeRcvFEZ3TYxo3UA==</xmpMM:InstanceID><dc:format>application/pdf</dc:format><pdf:PDFVersion>1.7</pdf:PDFVersion><dc:language><rdf:Bag></rdf:Bag></dc:language><xmpTPg:NPages>1</xmpTPg:NPages><xmpMM:RenditionClass>proof</xmpMM:RenditionClass></rdf:Description></rdf:RDF></x:xmpmeta><?xpacket end="r"?>
328c328
< 0000002424 00000 n
---
> 0000002440 00000 n
331,338c331,338
< 0000000647 00000 n
< 0000001137 00000 n
< 0000000894 00000 n
< 0000001835 00000 n
< 0000002605 00000 n
< 0000003097 00000 n
< 0000002857 00000 n
< 0000003796 00000 n
---
> 0000000650 00000 n
> 0000001139 00000 n
> 0000000900 00000 n
> 0000001837 00000 n
> 0000002618 00000 n
> 0000003111 00000 n
> 0000002867 00000 n
> 0000003810 00000 n
353c353
<   /ID [(HiQnxPhSaL50dAnsJIxLIQ==) (HiQnxPhSaL50dAnsJIxLIQ==)]
---
>   /ID [(U7DI7lZeRcvFEZ3TYxo3UA==) (U7DI7lZeRcvFEZ3TYxo3UA==)]
```
