### ISSUE TITLE
Ability to `get` values of rules

### ISSUE THREAD

**Issue by michidk** [typst/typst#763]
I want to access the values of rules that I previously set/which are set in the current context.

### Workaround

It can be worked around by putting the values into variables first, then passing them to `set` and reusing them wherever needed. This, however, gets very messy when with multiple rules whose values need to be accessed.

Example:

```
let margins = (
    top: 1cm,
    bottom: 1cm,
    left: 1cm,
    right: 1cm
);
set page(margin: margins)
```

### Example use-case

I want to put some content inside the page margin. Therefore I need to access the margin values.

```
let margins = (
   top: 1cm,
   ...
);
set page(margin: margins)

let text = text(fill: red, size: 20pt, "Some text at the top of the page")
place(top,  {
  v(-margins.top)
  text
})
```

I think this would also be required to add "Falzmarken" to the letter template.

### Proposal

Maybe it could be implemented like this:

```
let margins = get page(margin)
```

**Comment by laurmaedje** [comment]
This is certainly desirable, and we want to support it medium-term, but unfortunately it's not quite as simple as having a `get` syntax. Consider the example below:
```
#set text(size: 10pt)
#let stuff = [Text is #get text(size) large]

#set text(size: 20pt)
#stuff
```
The text is actually 20pt large and `get` would need to reflect that.

**Comment by lingo** [comment]
Would this sort of construction be more appropriate?

```typst
#locate(loc => {
  Text size at this location is #get (loc, text(size)) 
 })
```

**Comment by laurmaedje** [comment]
That would work with a bit of compiler work, but its actually even overkill. What we'd need is something like:
```
#style(styles => {
  Text size at this location is #get (styles, text(size)) 
})
```

**Comment by AzazKamaz** [comment]
Instead of doing `get(styles, text(size))` maybe it is better to do `get(styles, text).size` where `get` returns `arguments` or `dictionary` type with just stored options.

It seems that it is a lot easier compiler work because we don't need to deal with extra identifier that does not exist and etc

**Comment by Beiri22** [comment]
Any progress on this topic? The last approach of AzazKamaz ```get(styles, text).size``` seems logically correct and very promising to me. Accessing those properties dynamically would be very beneficial for my template, as logo and other sizes are dependent on page size.

**Comment by laurmaedje** [comment]
I have some ideas for making this much better long-term, but it's not fleshed out and will take a while in any case. In the meantime, something like `get(styles, text).size` or `text.size(styles)` would certainly be an option.

**Comment by Beiri22** [comment]
Can you give any time estimate on when to establish the "intermediate" version?

Can you outline your long-term idea?

**Comment by laurmaedje** [comment]
I can't really give an estimate currently. If somebody wants to work on it, that'd be great. If I do it myself, I'll have to see when I find the time, can't make any promises. It shouldn't be very difficult, but there are some tricky parts, in particular _folded_ properties: These make it possible to have `#set rect(stroke: 2pt); #set rect(stroke: red)` and get the combination `2pt + red`. Supporting this with get will be difficult because the folding routines operate on strongly typed Rust types and not on dynamic Typst values.

The long-term idea would fundamentally change how Typst evaluates code. I'm not yet sure whether it will work. The idea is basically to make variable bindings lazy and able to react to the context they are placed in. One variable could then result in different values depending on the context it is used in.

```
#let s = 10pt + get text(size)
#set text(size: 10pt)
#s // prints 20pt
#set text(size: 20pt)
#s // prints 30pt
```

We also wouldn't need `style()` anymore, it would just be `measure(thing)`. Maybe we could even get rid of `locate` though I'm not sure about that.

**Comment by Beiri22** [comment]
Sounds very interesting! But could there by any cases that require non-lazy evaluation? When a cvs is read into a var, would that be lazily evaluated, too? Or would that only happen to dynamic properties? Do you consider explicitly defining lazyily and normally evaluated properties?
```
dyn s = 10pt + get text(size) // works like your example
let s = 10pt + get text(size) // could be 1) take the value at execution, or 2.) be forbidden
```

Such a fundamental rework might take some effort and time; but would eventually result in a more versatile language :-)

**Comment by laurmaedje** [comment]
I think for this to work properly everything needs to be lazy. For example, if you write `heading[my title]`, then the definition of `heading` can only affect the styling of `[my title]` if `[my title]` is evaluated lazily. 

Right now, you can conceptually the content type as being lazy while all other scripting is eager. (Content is eagerly evaluated into an intermediate representation that is then separately/lazily styled.)  For this reason, set, style, locate, etc. only work with content. The rework would make everything lazy and as a result everything could participate in the set & get system. For example, `upper("some string")` could also correctly react to language-specific uppercasing rules (by doing `get text(lang)` internally), even if the result is stored in a variable and used in different places. 

CSV loading into a variable would also be lazy. I'm still figuring out how extreme lazyness (which is typically a thing in functional programming languages) works together with Typst's more imperative programming style (assignments, for loops, etc.) but I'm optimistic that it can work out well.

**Comment by Beiri22** [comment]
> CSV loading into a variable would also be lazy. I'm still figuring out how extreme lazyness (which is typically a thing in functional programming languages) works together with Typst's more imperative programming style (assignments, for loops, etc.) but I'm optimistic that it can work out well.

Is there any risk, that extreme lazyness degenerates into latex's def macro kind of thing?

**Comment by laurmaedje** [comment]
I've also recently realized that extremely lazy functions sort of come close to macros. One big difference is that we still have proper scoping and hygienic name resolution. Functions would also continue to be pure (they'd just have an implicit context parameter, basically). Do you have any particular concerns how this degeneration to macro could cause problems?

**Comment by Beiri22** [comment]
It's mainly an unspecific feeling...

**Comment by ntjess** [comment]
Consider also that e.g. page margin, stroke, etc. boil down to several sub-properties. I suggest instead of `get page(margin)`, the user is required to specify the highest granularity:

`get page(marign.left)` or `get rect(stroke.paint)`.

This prevents the ambiguous case that they are getting a margin where top, left, and bottom each have separate values.

Alternatively, nested scopes:

`get page(get margin(left))`

Or method accessors

`page.get("margin.left")`

Thoughts?

**Comment by laurmaedje** [comment]
I would have thought that `get page(margin)` just returns the full thing and then you can do `(get page(margin)).left` or `get page(margin).left` (if we allow that precedence-wise). With a different syntax, we would maybe not have the precedence weirdness.

**Comment by ntjess** [comment]
What about just `get page`? And you can access fields like margin, etc. This allows getting multiple properties at once, similar to how multiple can be `set` at once

Sample use:

```
let properties = get page
properties.width, properties.margin.left
```

Otherwise, I am curious what the return value would be for `get page(margin, width)`

The alternative nested syntax also handles this somewhat well

```
get page {
  let margin = get(margin)
  let width = get(width)
}
```

But this might be too much complexity

**Comment by laurmaedje** [comment]
Might be a little inefficient when there are many properties, but could be an option!

**Comment by ramkumarkb** [comment]
@laurmaedje  - I have a related question to this issue - will I be able to `query` all the `heading` in a page. The current function allows me to query either `before` or `after` loc - but this does not help when I want to show the heading (with number) in the header of a page. If am able to introspec all the headings in a page - then based on the usecase I can select the first or the last one for the header... 

```
query(
      selector(heading).after(loc),
    loc,
    )
```

**Comment by Beiri22** [comment]
Have you tried 
```typc
query(heading, loc)
```

**Comment by ramkumarkb** [comment]
@Beiri22 - Yes, I did but it just returned all the headings in the document. How do I query the Headings in the `current page`?

**Comment by ntjess** [comment]
```typst
= A heading

#pagebreak()

= Another heading

= A second heading on the second page

#pagebreak()
#locate(loc => {
  query(heading, loc).map(it => it.location().position().page)
})
```
![image](https://github.com/typst/typst/assets/23620506/619065a5-3a64-4163-883c-0e3ce7445ce7)

You can filter for just the headings where the page matches `loc`'s page

**Comment by Beiri22** [comment]
> @Beiri22 - Yes, I did but it just returned all the headings in the document. How do I query the Headings in the `current page`?

I'm sorry, I just read half of you question, that's why I have deleted this comment. But ntjess' comment looks promising

**Comment by ramkumarkb** [comment]
@ntjess  - Thank you, this works.

```
#set heading(numbering: "1.")

#set page(header: locate(loc => {
  let elems = query(
    selector(heading).before(loc),
    loc,
  )
  let academy = smallcaps[
    Typst Academy
  ]
  if elems == () {
    align(right, academy)
  } else {
    
    let title = elems.last().body

    // find all the heading pages
    let pgs = query(heading, loc).map(it => it.location().position().page)

    // get the current page
    let currpage = loc.page()

    if pgs.contains(currpage) {
      // title = "test"
      title = query(heading, loc).filter(it => (it.location().position().page == currpage)).first().body
    }

    academy + h(1fr) + [#emph(title)]
  }
}))

= Introduction
#lorem(2300)

#pagebreak()
= Background
#lorem(30)

// #pagebreak()
= Analysis
#lorem(15)
```

**Comment by Beiri22** [comment]
> Might be a little inefficient when there are many properties, but could be an option!
It would not be so inefficient, when we lazy load the properties, right?

**Comment by Beiri22** [comment]
> > Might be a little inefficient when there are many properties, but could be an option!

It would not be so inefficient, when we lazy load the properties, right? But that is an even larger change to the system.

**Comment by Beiri22** [comment]
@laurmaedje I've been looking into the sources. Please help me. When implementing a get rule you would `impl Eval for ast::GetRule` in `typst/eval/mod.rs` (plus some more infrastruture. As far as I understand, set rules push those information into `styles`. How could you retrieve the styles of the target of a get rule, when `impl Eval` supplies the `eval` function with only `&self, vm: &mut Vm`?

**Comment by Beiri22** [comment]
I have this proposal: A get function to `styles`, that can be retrieved via `styles()`

**Comment by fredguth** [comment]
> I've also recently realized that extremely lazy functions sort of come close to macros. One big difference is that we still have proper scoping and hygienic name resolution. Functions would also continue to be pure (they'd just have an implicit context parameter, basically). Do you have any particular concerns how this degeneration to macro could cause problems?

You can have this kind of lazy evaluation by using an `observer` pattern.  I have never programmed in `Rust` but I guess there is a way to have the page properties be reactive (similar to $props in svelte, for example).  Using the observer pattern you only calculate the values you actually need.

**Comment by SebastianJL** [comment]
Hello everyone
I just wanted to ask if there is any progress to this :)

**Comment by Beiri22** [comment]
Hi Sebastian,
if you join the typst discord; there's a category forge / and the subitem should be Contexts. There is not much to read right now; but it's the place to look and discuss.

**Comment by laurmaedje** [comment]
Resolved by https://github.com/typst/typst/pull/3497.

**Comment by memeplex** [comment]
I've been trying this in 0.11.0 but still have a question. When margin is set to auto, is there a way to get the actual size without recomputing:

> The margins are set automatically to 2.5/21 times the smaller dimension of the page.

which is repetitive and error prone if the definition of auto were to change in the future?

**Comment by Beiri22** [comment]
I think there is some discussion in the developer chat about that...

**Comment by laurmaedje** [comment]
We might resolve more of those `auto` values automatically in the future, but for now, you'll have to do it manually.

**Comment by jeertmans** [comment]
> Resolved by #3497.

Hello @laurmaedje, after trying a bit with `context`, I cannot use it as default, e.g., I would like to be able to do that:

```typst
#let function(text-size: context text.size) {
   set text(size: text-size)
}
```

but it fails because it says:

```
[17:35:15] compiled with errors

error: expected length, found content
   ┌─ template.typ:52:21
   │
52 │       set text(size: text-size)
   │                      ^^^^^^^^^
```

And I could not find many usage examples of `context` online, so I was wondering how to actually use it to specify default values with it?

**Comment by MDLC01** [comment]
This is because a context block always returns content. In this case, `context text.size` evaluates to some content that contains a representation of the text size. To do what you want, you have to use a guard value, such as `auto`:
```typ
#let function(text-size: auto) {
  context {
    if text-size == auto {
      text-size = text.size
    }
    set text(size: text-size)
  }
}
```

Also note that using a set rule in a block without anything after won't do anything, as a set rule only applies to content that appears between it and the end of its block:
```typ
#{
  set text(color: red)
  [This is red.]
} // Anything after this closing brace won't be affected by the set rule.
This is not.
```

**Comment by jeertmans** [comment]
> This is because a context block always returns content. In this case, `context text.size` evaluates to some content that contains a representation of the text size. To do what you want, you have to use a guard value, such as `auto`:
> 
> ```typst
> #let function(text-size: auto) {
>   context {
>     if text-size == auto {
>       text-size = text.size
>     }
>     set text(size: text-size)
>   }
> }
> ```
> 
> Also note that using a set rule in a block without anything after won't do anything, as a set rule only applies to content that appears between it and the end of its block:
> 
> ```typst
> #{
>   set text(color: red)
>   [This is red.]
> } // Anything after this closing brace won't be affected by the set rule.
> This is not.
> ```

Hey @MDLC01, thanks for your reply, and sorry for mine being late!

Just to indicate that the above does not work because you cannot mutate variables that are declared outside the `context` scope, but an easy workaround to this is to declare a local variable, e.g.,

```typst
#let function(text-size: auto) {
  context {
    let size = text-size
    if text-size == auto {
      size = text.size
    }
    set text(size: size)
  }
}
```
